name: "Migrate cases"
on:
  workflow_dispatch:

  schedule:
    - cron:  '0 10-22/1 * * *'

jobs:
  migrate_cases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        court: [santabarbara, delnorte]
        server: [live]
    name: ${{ matrix.court }}.${{ matrix.server }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          config: ${{ secrets.SSH_CONFIG }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      - name: Stop running migrations
        continue-on-error: true
        run: |
          terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- migrate:stop case_node_civil_cases
          terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- migrate:stop case_node_criminal_cases
          terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- migrate:stop case_node_traffic_cases
      - name: Reset migrations
        continue-on-error: true
        run: |
          terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- migrate:reset case_node_civil_cases
          terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- migrate:reset case_node_criminal_cases
          terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- migrate:reset case_node_traffic_cases
      - name: Migrate Civil Cases
        continue-on-error: true
        run: terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- migrate:import case_node_civil_cases
      - name: Migrate Criminal Cases
        continue-on-error: true
        run: terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- migrate:import case_node_criminal_cases
      - name: Migrate Traffic Cases
        continue-on-error: true
        run: terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- migrate:import case_node_traffic_cases
      - name: Clear cache
        continue-on-error: true
        run: terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- cr
