name: "Migrate filed cases: Supreme Court"
on:
  workflow_dispatch:

  schedule:
    # Every Tuesday at 7:30 AM Pacific (14:30 UTC).
    - cron:  '30 14 * * 2'

jobs:
  migrate_filed_cases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        court: [supremecourt]
        server: [live]
    name: ${{ matrix.court }}.${{ matrix.server }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          config: ${{ secrets.SSH_CONFIG }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      - name: Stop running migrations
        continue-on-error: true
        run: |
          terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- migrate:stop sc_filed_cases
      - name: Reset migrations
        continue-on-error: true
        run: |
          terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- migrate:reset sc_filed_cases
      - name: Migrate filed cases
        continue-on-error: true
        run: terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- migrate:import sc_filed_cases
      - name: Clear cache
        continue-on-error: true
        run: terminus drush jcc-${{ matrix.court }}.${{ matrix.server }} -- cr
