name: "Migrate civil cases"
on:
  schedule:
    - cron:  '*/30 * * * *'    # at every 10 minutes

jobs:
  terminus_drush:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          config: ${{ secrets.SSH_CONFIG }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

      - name: Migrate Santa Barbara Civil Cases via Terminus Drush
        run: terminus drush jcc-santabarbara.develop -- migrate:import case_node_civil_cases --continue-on-failure
